version: '3.7'
services:
  sfmworker:
    build: .
    image: sfm-worker-img
    container_name: sfm-worker
    volumes:
      - .:/sfmworker
    command: python3.10 main.py --run_mode
    networks:
      - backend 
    ports: 
      - 5100:5100

networks:
  backend:
    name: backend-network
    external: true
